--Normal maps
    vim.api.nvim_set_keymap("n","<C-o>","i/*<ESC>")
    vim.api.nvim_set_keymap("n","<C-c>","a*/<ESC>")
    vim.api.nvim_set_keymap("n","<C-s>",":setlocal spell!<cr>")
    vim.api.nvim_set_keymap("n","<S-k>","<Nop>")
    vim.api.nvim_set_keymap("n","mm",":nohl<ENTER>")
    vim.api.nvim_set_keymap("n","<M-j>","<DOWN>zj<UP>")
    vim.api.nvim_set_keymap("n","<M-k>","zk<UP>")
    vim.api.nvim_set_keymap("n","<M-u>","[z")
    vim.api.nvim_set_keymap("n","<M-d>","]z")
    vim.api.nvim_set_keymap("n","<leader>ti","i["+string(i)+"]<ESC>")
    vim.api.nvim_set_keymap("n","<leader>vv",":execute "Ack! " expand("<cword>")<CR>")
    vim.api.nvim_set_keymap("n","<leader>gff",":e scripts\\<c-r><c-w>\\<c-r><c-w>.gml<CR>")
    vim.api.nvim_set_keymap("n","<leader>gfv",":vs scripts\\<c-r><c-w>\\<c-r><c-w>.gml<CR>")
    vim.api.nvim_set_keymap("n","<leader>gfs",":sp scripts\\<c-r><c-w>\\<c-r><c-w>.gml<CR>")
    vim.api.nvim_set_keymap("n","<Space>","@")
    vim.api.nvim_set_keymap("n","<C-J>","<C-W><C-J>")
    vim.api.nvim_set_keymap("n","<C-H>","<C-W><C-H>")
    vim.api.nvim_set_keymap("n","<C-K>","<C-W><C-K>")
    vim.api.nvim_set_keymap("n","<C-L>","<C-W><C-L>")
    vim.api.nvim_set_keymap("n","<S-H>","gT")
    vim.api.nvim_set_keymap("n","<S-L>","gt")
    vim.api.nvim_set_keymap("n","<silent>","<C-T> :tabe<CR>")
    vim.api.nvim_set_keymap("n","<silent>","<S-T> :tabclose<CR>")
    vim.api.nvim_set_keymap("n","<M-s>",":m .+1<CR>==")
    vim.api.nvim_set_keymap("n","<M-w>",":m .-2<CR>==")
    vim.api.nvim_set_keymap("n","<leader>bd",":call DeleteHiddenBuffers()<CR>")
    vim.api.nvim_set_keymap("n","<leader>sda",":cd %:p:h<CR>:cd<CR>")
    vim.api.nvim_set_keymap("n","<leader>sdw",":lcd %:p:h<CR>:cd<CR>")
    vim.api.nvim_set_keymap("n","<leader>//"," /\<\><LEFT><LEFT>")
    vim.api.nvim_set_keymap("n","<leader>/f"," /function ")
    vim.api.nvim_set_keymap("n","<leader>ltb","b:let timer=timer_start(500,'UpdateFile',{'repeat':-1})<CR>")
    vim.api.nvim_set_keymap("n","<leader>lte",":call timer_stopall()<CR>")
    vim.api.nvim_set_keymap("n","<leader>eko1",":call SetLog1()<CR>")
    vim.api.nvim_set_keymap("n","<leader>eko2",":call SetLog2()<CR>")
    vim.api.nvim_set_keymap("n","<leader>eko3",":call SetLog3()<CR>")
    vim.api.nvim_set_keymap("n","<leader>eko4",":call SetLog4()<CR>")
    vim.api.nvim_set_keymap("n","<leader>ogml",":term ++curwin datafiles\Gmlive\gmlive-server.exe<CR>")
    vim.api.nvim_set_keymap("n","+","<C-w>+")
    vim.api.nvim_set_keymap("n","-","<C-w>-")
    vim.api.nvim_set_keymap("n","z-",":set foldnestmax=1<CR>")
    vim.api.nvim_set_keymap("n","z+",":set foldnestmax=2<CR>")
    vim.api.nvim_set_keymap("n","<leader>bw",":BW<CR>")
    vim.api.nvim_set_keymap("n","<silent>","<leader>sv :so $MYVIMRC<CR>:Syndo filetype detect<CR>")
    vim.api.nvim_set_keymap("n","<silent>","<leader>ev :e $MYVIMRC<CR>")
    vim.api.nvim_set_keymap("n","<leader>ve",":e C:\\Program Files (x86)\\Vim\\Vimfiles\\")
    vim.api.nvim_set_keymap("n","<silent>","<leader>eg :e C:\\Users\\Psy\AppData\\Local\\nvim\\syntax\\gml.vim<CR>")
    vim.api.nvim_set_keymap("n","<leader>ek",":e C:\\Users\\Psy\\Appdata\\Roaming\\")
    vim.api.nvim_set_keymap("n","<silent>","<leader>oo :only<CR>")
    vim.api.nvim_set_keymap("n","<F6>",":w<ENTER>:!%<ENTER>")
    vim.api.nvim_set_keymap("n","<F2>",":Syndo filetype detect<CR>")
    vim.api.nvim_set_keymap("n","<F3>",":let t:mytablabel = ''<Left>")
    --GAMEMAKER MACROS
    vim.api.nvim_set_keymap("n","<silent>",'<leader>tt yiwiTrace("<ESC>A: "+string());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>td yiwiGuiTrace("<ESC>A: ",);<ESC>hP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>to yiwiTrace("<ESC>A: "+object_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>ts yiwiTrace("<ESC>A: "+sprite_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>tc yiwiTrace("<ESC>A: "+script_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>ta yiwiTrace("<ESC>A: "+audio_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>tr yiwiTrace("<ESC>A: "+room_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>tb yiwiTrace("<ESC>A: "+rb());<ESC>hhP')
    vim.api.nvim_set_keymap("n","<silent>",'<leader>cd o_text = "<ESC>pa: " + string(<ESC>pa);<CR>draw_text_transformed(_tx, _ty, _tt, .25, .25, 0);<ESC>')
    vim.api.nvim_set_keymap("n","<silent><leader>cv","oTrace_string('<ESC>pa');<ESC>kdd")
    vim.api.nvim_set_keymap("n",'<silent><leader>cz','oTrace(": " + string());<ESC>2F"pf(p<UP>dd<DOWN>f:')
    vim.api.nvim_set_keymap("n","<silent><leader>sd","oTrace("");<ESC>2hi")
    vim.api.nvim_set_keymap("n","<silent><leader>cx",'oTrace(""+string());<ESC>F"i')
    vim.api.nvim_set_keymap("n","<silent><leader>cs","oTrace("--CALLSTACK--");for(var i=0,cs=debug_get_callstack();i<array_length(cs);i++) Trace(cs[i]);<ESC>")
    vim.api.nvim_set_keymap("n","<silent><leader>tp","^eaPop<ESC>")
    vim.api.nvim_set_keymap("n","<silent><leader>ww","o//<ESC>90a=<ESC>a\\<CR>//<ESC>90a<SPACE><ESC>a\|\|<ESC>o//<ESC>90a=<ESC>A//<ESC>kk^llR@PsychoMale<ESC>j")

    vim.api.nvim_set_keymap("n","<silent><leader>wd","v$3hxjjv$3hx")

    vim.api.nvim_set_keymap("n","<silent><leader>fi","ofor(var i=0;i<;i++){2f;i")
    vim.api.nvim_set_keymap("n","<silent><leader>fj","ofor(var j=0;j<;j++){2f;i")
    vim.api.nvim_set_keymap("n","<silent><leader>fk","ofor(var k=0;k<;k++){2f;i")
    vim.api.nvim_set_keymap("n","<silent><leader>fl","ofor(var l=0;l<;l++){2f;i")
    vim.api.nvim_set_keymap("n","<silent><leader>fm","ofor(var i=ds_map_find_first(_map);IsDefined(i);i=ds_map_find_next(_map,i)){o")

    vim.api.nvim_set_keymap("n","<silent><leader>br","oBreakpoint();<ESC>")

    vim.api.nvim_set_keymap("n","<silent><leader>cw",'f"lvf"h~')
    vim.api.nvim_set_keymap("n","<leader><mks>",":mks! C:\\sess\\")
    vim.api.nvim_set_keymap("n","<leader><src>",":source! C:\\sess\\")
    vim.api.nvim_set_keymap("n","<F1>",":mks! C:\sess\1.vim<CR>")
    vim.api.nvim_set_keymap("n","<silent><leader>s1",":source C:\\sess\\1.vim<CR>")
    vim.api.nvim_set_keymap("n","<silent><leader>vw",":vs<CR>")
    vim.api.nvim_set_keymap("n","<silent><leader>sw",":sp<CR><C-W><C-J>")
    vim.api.nvim_set_keymap("n","","   nmap <silent><leader>fl vBxafor(var i=0;i<ds_list_size(<ESC>pa);i++){o")
    vim.api.nvim_set_keymap("n","<silent><leader>fa","vBxafor(var i=0;i<array_length(<ESC>pa);i++){o")
    vim.api.nvim_set_keymap("n","<silent><leader>fw","vBxafor(var i=0;i<ds_grid_width(<ESC>pa);i++){o")
    vim.api.nvim_set_keymap("n","<silent><leader>fh","vBxafor(var i=0;i<ds_grid_height(<ESC>pa);i++){o")
    vim.api.nvim_set_keymap("n","<silent><leader>te","otry{jacatch(e){oTraceException(e);<ESC>")
    --ESC MAPS
    --GAMEMAKER FILE EDITING
    vim.api.nvim_set_keymap("n","<ESC>eo",":e  objects\\")
    vim.api.nvim_set_keymap("n","<ESC>vo",":vs objects\\")
    vim.api.nvim_set_keymap("n","<ESC>so",":sp objects\\")

    vim.api.nvim_set_keymap("n","<ESC>es",":e  scripts\\")
    vim.api.nvim_set_keymap("n","<ESC>vs",":vs scripts\\")
    vim.api.nvim_set_keymap("n","<ESC>ss",":sp scripts\\")

    vim.api.nvim_set_keymap("n","<ESC>er",":e  rooms\\")
    vim.api.nvim_set_keymap("n","<ESC>vr",":vs rooms\\")
    vim.api.nvim_set_keymap("n","<ESC>sr",":sp rooms\\")

    vim.api.nvim_set_keymap("n","<ESC>ed",":e  datafiles\\")
    vim.api.nvim_set_keymap("n","<ESC>vd",":vs datafiles\\")
    vim.api.nvim_set_keymap("n","<ESC>sd",":sp datafiles\\")

    vim.api.nvim_set_keymap("n","<ESC>ea",":e  shaders\\")
    vim.api.nvim_set_keymap("n","<ESC>va",":vs shaders\\")
    vim.api.nvim_set_keymap("n","<ESC>sa",":sp shaders\\")

    vim.api.nvim_set_keymap("n","<ESC>eu",":e  sounds\\")
    vim.api.nvim_set_keymap("n","<ESC>vu",":vs sounds\\")
    vim.api.nvim_set_keymap("n","<ESC>su",":sp sounds\\")

    vim.api.nvim_set_keymap("n","<ESC>en",":e  notes\\")
    vim.api.nvim_set_keymap("n","<ESC>vn",":vs notes\\")
    vim.api.nvim_set_keymap("n","<ESC>sn",":sp notes\\")

    vim.api.nvim_set_keymap("n","<ESC>to",":tabe objects\\")
    vim.api.nvim_set_keymap("n","<ESC>ts",":tabe scripts\\")
    vim.api.nvim_set_keymap("n","<ESC>tr",":tabe rooms\\")
    vim.api.nvim_set_keymap("n","<ESC>td",":tabe datafiles\\")
    vim.api.nvim_set_keymap("n","<ESC>ta",":tabe shaders\\")
    vim.api.nvim_set_keymap("n","<ESC>tn",":tabe notes\\")

    vim.api.nvim_set_keymap("n","<leader>,e",":e <C-R>=expand("%:.:h") . "\\" <CR>")
    vim.api.nvim_set_keymap("n","<leader>,s",":split <C-R>=expand("%:.:h") . "\\" <CR>")
    vim.api.nvim_set_keymap("n","<leader>,v",":vs <C-R>=expand("%:.:h") . "\\" <CR>")
    vim.api.nvim_set_keymap("n","<leader>,t",":tabe <C-R>=expand('%:.:h') . "\\" <CR>")

    vim.api.nvim_set_keymap("n","<C-_>-","<C-W>-")
    --Cursor line/column highlight toggle
    vim.api.nvim_set_keymap("n","<silent>","<TAB>cc    :Windo set cuc<CR>:Windo set cul<CR>")
    vim.api.nvim_set_keymap("n","<silent>","<TAB>ch    :Windo set nocuc<CR>:Windo set nocul<CR>")
    --Quick Indent/Unindent
    vim.api.nvim_set_keymap("n","<TAB>ik","kvj^f{%j>")
    vim.api.nvim_set_keymap("n","<TAB>ij","jvk^f{%k>")
    vim.api.nvim_set_keymap("n","<TAB>uk","kvj^f{%j<")
    vim.api.nvim_set_keymap("n","<TAB>uj","jvk^f{%k<")
    vim.api.nvim_set_keymap("n","<TAB>kz","V$%zf")
    vim.api.nvim_set_keymap("n","<TAB>jz","V$%zf")
    vim.api.nvim_set_keymap("n","<TAB><CR>","s{ja<CR><ESC>ddkP>>")
    vim.api.nvim_set_keymap("n","<leader>str","a={ofunc:function(){ja,<ESC>2kI")
    vim.api.nvim_set_keymap("n","dq","df_")
    vim.api.nvim_set_keymap("n","dQ","dt_")
    vim.api.nvim_set_keymap("n","Q"," :E %:h../..<CR>")
    vim.api.nvim_set_keymap("n","<leader>drw","idraw_sprite(sprite_index,image_index,x,y);<ESC>")
    vim.api.nvim_set_keymap("n","<leader>dre","idraw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha);<ESC>")
    vim.api.nvim_set_keymap("n","<leader>gmf","k^wvt(yolive_name='<C-R>';<ESC>")
    vim.api.nvim_set_keymap("n","<leader>gml","Oif(live_call()) return live_result;<ESC>")
    -- Find files using Telescope command-line sugar.
    vim.api.nvim_set_keymap("n","<leader>ff","<cmd>Telescope find_files<cr>")
    vim.api.nvim_set_keymap("n","<leader>fg","<cmd>Telescope live_grep<cr>")
    vim.api.nvim_set_keymap("n","<leader>fb","<cmd>Telescope buffers<cr>")
    --nnoremap <leader>fh <cmd>Telescope help_tags<cr>
    -- NVim Tree
    vim.api.nvim_set_keymap("n","<leader>ntt","<cmd>NvimTreeToggle<cr>")
    vim.api.nvim_set_keymap("n","<leader>ntf","<cmd>NvimTreeFocus<cr>")
    vim.api.nvim_set_keymap("n","<leader>ntc","<cmd>NvimTreeCollapse<cr>")
    -- Fold method
    vim.api.nvim_set_keymap("n","<leader>fm","<cmd>set foldmethod=marker<cr>")
    vim.api.nvim_set_keymap("n","<leader>fi","<cmd>set foldmethod=indent<cr>")
    vim.api.nvim_set_keymap("n","<leader>fe","<cmd>set foldmethod=expr<cr>")
    vim.api.nvim_set_keymap("n","<leader>cdk","<cmd>cd Kalyzmyr<cr>")
    vim.api.nvim_set_keymap("n","<leader>cdd","<cmd>cd Dekamara<cr>")
    vim.api.nvim_set_keymap("n","<leader>cdl","<cmd>cd Kingdom Lost Reborn<cr>")
--Visual maps
    vim.api.nvim_set_keymap("v","//","y/\\V<C-R>=escape(@','/\\')<CR><CR>'")
    vim.api.nvim_set_keymap("v","<S-x>",":s/y/x/g<CR>:nohl<CR>")
    vim.api.nvim_set_keymap("v","<S-y>",":s/x/y/g<CR>:nohl<CR>")

    vim.api.nvim_set_keymap("v","<leader>vv","y:execute 'Ack! -G .gml <C-R>'<CR>")
    vim.api.nvim_set_keymap("v","<leader>p","_dP")

    vim.api.nvim_set_keymap("v","<silent><leader>tt",'yiTrace("<ESC>A: "+string());<ESC>hhP')
    vim.api.nvim_set_keymap("v","<silent><leader>td",'yiGuiTrace("<ESC>A: ",);<ESC>hP')
    vim.api.nvim_set_keymap("v","<silent><leader>to",'yiTrace("<ESC>A: "+object_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("v","<silent><leader>ts",'yiTrace("<ESC>A: "+sprite_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("v","<silent><leader>tc",'yiTrace("<ESC>A: "+script_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("v","<silent><leader>ta",'yiTrace("<ESC>A: "+audio_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("v","<silent><leader>tr",'yiTrace("<ESC>A: "+room_get_name());<ESC>hhP')
    vim.api.nvim_set_keymap("v","<silent><leader>tb",'yiTrace("<ESC>A: "+rb());<ESC>hhP')


--Insert maps                                                                                
    vim.api.nvim_set_keymap("i","{","{<CR>}<ESC><UP>")
    vim.api.nvim_set_keymap("i","<C-S-CR>","{}<LEFT>")
    vim.api.nvim_set_keymap("i","<M-[>","[]<LEFT>")
    vim.api.nvim_set_keymap("i","<M-'>","<LEFT>")
    vim.api.nvim_set_keymap("i","<C-CR>","{<CR>}else{<CR>}<ESC><UP><UP>")
    vim.api.nvim_set_keymap("i","<S-CR>","{<CR>}<ESC>O")
    vim.api.nvim_set_keymap("i","<C-SPACE>","<TAB>=")
    vim.api.nvim_set_keymap("i","<S-SPACE>","_")
    vim.api.nvim_set_keymap("i","<S-ESC>","<ESC>:w<CR>")
