--Normal maps
    vim.keymap.set("n","<C-o>","i/*<ESC>")
    vim.keymap.set("n","<C-c>","a*/<ESC>")
    vim.keymap.set("n","<C-s>",":setlocal spell!<cr>")
    vim.keymap.set("n","<S-k>","<Nop>")
    vim.keymap.set("n","mm",":nohl<ENTER>")
    vim.keymap.set("n","<M-j>","<DOWN>zj<UP>")
    vim.keymap.set("n","<M-k>","zk<UP>")
    vim.keymap.set("n","<M-u>","[z")
    vim.keymap.set("n","<M-d>","]z")
    vim.keymap.set("n","<leader>ti","i['+string(i)+']<ESC>")
    vim.keymap.set("n","<leader>vv",":execute 'Ack! ' expand('<cword>')<CR>")
    vim.keymap.set("n","<leader>gff",":e scripts\\<c-r><c-w>\\<c-r><c-w>.gml<CR>")
    vim.keymap.set("n","<leader>gfv",":vs scripts\\<c-r><c-w>\\<c-r><c-w>.gml<CR>")
    vim.keymap.set("n","<leader>gfs",":sp scripts\\<c-r><c-w>\\<c-r><c-w>.gml<CR>")
    vim.keymap.set("n","<Space>","@")
    vim.keymap.set("n","<C-J>","<C-W><C-J>")
    vim.keymap.set("n","<C-H>","<C-W><C-H>")
    vim.keymap.set("n","<C-K>","<C-W><C-K>")
    vim.keymap.set("n","<C-L>","<C-W><C-L>")
    vim.keymap.set("n","<S-H>","gT")
    vim.keymap.set("n","<S-L>","gt")
    vim.keymap.set("n","<C-T>",":tabe<CR>")
    vim.keymap.set("n","<S-T>",":tabclose<CR>")
    vim.keymap.set("n","<M-s>",":m .+1<CR>==")
    vim.keymap.set("n","<M-w>",":m .-2<CR>==")
    vim.keymap.set("n","<leader>bd",":call DeleteHiddenBuffers()<CR>")
    vim.keymap.set("n","<leader>sda",":cd %:p:h<CR>:cd<CR>")
    vim.keymap.set("n","<leader>sdw",":lcd %:p:h<CR>:cd<CR>")
    vim.keymap.set("n","<leader>//"," /\\<\\><LEFT><LEFT>")
    vim.keymap.set("n","<leader>/f"," /function ")
    vim.keymap.set("n","<leader>ltb","b:let timer=timer_start(500,'UpdateFile',{'repeat':-1})<CR>")
    vim.keymap.set("n","<leader>lte",":call timer_stopall()<CR>")
    vim.keymap.set("n","<leader>eko1",":call SetLog1()<CR>")
    vim.keymap.set("n","<leader>eko2",":call SetLog2()<CR>")
    vim.keymap.set("n","<leader>eko3",":call SetLog3()<CR>")
    vim.keymap.set("n","<leader>eko4",":call SetLog4()<CR>")
    vim.keymap.set("n","<leader>ogml",":term ++curwin datafiles\\Gmlive\\gmlive-server.exe<CR>")
    vim.keymap.set("n","+","<C-w>+")
    vim.keymap.set("n","-","<C-w>-")
    vim.keymap.set("n","z-",":set foldnestmax=1<CR>")
    vim.keymap.set("n","z+",":set foldnestmax=2<CR>")
    vim.keymap.set("n","<leader>bw",":BW<CR>")
    vim.keymap.set("n","<leader>sv",":so $MYVIMRC<CR>")
    vim.keymap.set("n","<leader>ev",":e $MYVIMRC<CR>")
    vim.keymap.set("n","<leader>ve",":e C:\\Program Files (x86)\\Vim\\Vimfiles\\")
    vim.keymap.set("n","<leader>eg",":e C:\\Users\\Psy\\AppData\\Local\\nvim\\syntax\\gml.vim<CR>")
    vim.keymap.set("n","<leader>ek",":e C:\\Users\\Psy\\Appdata\\Roaming\\")
    vim.keymap.set("n","<leader>oo",":only<CR>")
    vim.keymap.set("n","<F6>",":w<ENTER>:!%<ENTER>")
    --GAMEMAKER MACROS
    vim.keymap.set("n","<leader>tt","yiwiTrace('<ESC>A: '+string());<ESC>hhP")
    vim.keymap.set("n","<leader>td","yiwiGuiTrace('<ESC>A: ',);<ESC>hP")
    vim.keymap.set("n","<leader>to","yiwiTrace('<ESC>A: '+object_get_name());<ESC>hhP")
    vim.keymap.set("n","<leader>ts","yiwiTrace('<ESC>A: '+sprite_get_name());<ESC>hhP")
    vim.keymap.set("n","<leader>tc","yiwiTrace('<ESC>A: '+script_get_name());<ESC>hhP")
    vim.keymap.set("n","<leader>ta","yiwiTrace('<ESC>A: '+audio_get_name());<ESC>hhP")
    vim.keymap.set("n","<leader>tr","yiwiTrace('<ESC>A: '+room_get_name());<ESC>hhP")
    vim.keymap.set("n","<leader>tb","yiwiTrace('<ESC>A: '+rb());<ESC>hhP")
    vim.keymap.set("n","<leader>cd","o_text = '<ESC>pa: ' + string(<ESC>pa);<CR>draw_text_transformed(_tx, _ty, _tt, .25, .25, 0);<ESC>")
    vim.keymap.set("n","<leader>cv","oTrace_string('<ESC>pa');<ESC>kdd")
    vim.keymap.set("n","<leader>cz",'oTrace(": " + string());<ESC>2F"pf(p<UP>dd<DOWN>f:')
    vim.keymap.set("n","<leader>sd",'oTrace("");<ESC>2hi')
    vim.keymap.set("n","<leader>cx",'oTrace(""+string());<ESC>F"i')
    vim.keymap.set("n","<leader>cs","oTrace('--CALLSTACK--');for(var i=0,cs=debug_get_callstack();i<array_length(cs);i++) Trace(cs[i]);<ESC>")
    vim.keymap.set("n","<leader>tp","^eaPop<ESC>")
    vim.keymap.set("n","<leader>ww","o//<ESC>90a=<ESC>a\\\\<CR>//<ESC>90a<SPACE><ESC>a||<ESC>o//<ESC>90a=<ESC>A//<ESC>kk^llR@PsychoMale<ESC>j")

    vim.keymap.set("n","<leader>wd","v$3hxjjv$3hx")

    vim.keymap.set("n","<leader>fi","ofor(var i=0;i<;i++){2f;i")
    vim.keymap.set("n","<leader>fj","ofor(var j=0;j<;j++){2f;i")
    vim.keymap.set("n","<leader>fk","ofor(var k=0;k<;k++){2f;i")
    vim.keymap.set("n","<leader>fl","ofor(var l=0;l<;l++){2f;i")
    vim.keymap.set("n","<leader>fm","ofor(var i=ds_map_find_first(_map);IsDefined(i);i=ds_map_find_next(_map,i)){o")

    vim.keymap.set("n","<leader>br","oBreakpoint();<ESC>")

    vim.keymap.set("n","<leader>cw",'f"lvf"h~')
    vim.keymap.set("n","<leader><mks>",":mks! C:\\sess\\")
    vim.keymap.set("n","<leader><src>",":source! C:\\sess\\")
    vim.keymap.set("n","<F1>",":mks! C:\\sess\\1.vim<CR>")
    vim.keymap.set("n","<leader>s1",":source C:\\sess\\1.vim<CR>")
    vim.keymap.set("n","<leader>vw",":vs<CR>")
    vim.keymap.set("n","<leader>sw",":sp<CR><C-W><C-J>")
    vim.keymap.set("n","<leader>fl","vBxafor(var i=0;i<ds_list_size(<ESC>pa);i++){o")
    vim.keymap.set("n","<leader>fa","vBxafor(var i=0;i<array_length(<ESC>pa);i++){o")
    vim.keymap.set("n","<leader>fw","vBxafor(var i=0;i<ds_grid_width(<ESC>pa);i++){o")
    vim.keymap.set("n","<leader>fh","vBxafor(var i=0;i<ds_grid_height(<ESC>pa);i++){o")
    vim.keymap.set("n","<leader>te","otry{jacatch(e){oTraceException(e);<ESC>")
    --ESC MAPS
    --GAMEMAKER FILE EDITING
    vim.keymap.set("n","<ESC>eo",":e  objects\\")
    vim.keymap.set("n","<ESC>vo",":vs objects\\")
    vim.keymap.set("n","<ESC>so",":sp objects\\")

    vim.keymap.set("n","<ESC>es",":e  scripts\\")
    vim.keymap.set("n","<ESC>vs",":vs scripts\\")
    vim.keymap.set("n","<ESC>ss",":sp scripts\\")

    vim.keymap.set("n","<ESC>er",":e  rooms\\")
    vim.keymap.set("n","<ESC>vr",":vs rooms\\")
    vim.keymap.set("n","<ESC>sr",":sp rooms\\")

    vim.keymap.set("n","<ESC>ed",":e  datafiles\\")
    vim.keymap.set("n","<ESC>vd",":vs datafiles\\")
    vim.keymap.set("n","<ESC>sd",":sp datafiles\\")

    vim.keymap.set("n","<ESC>ea",":e  shaders\\")
    vim.keymap.set("n","<ESC>va",":vs shaders\\")
    vim.keymap.set("n","<ESC>sa",":sp shaders\\")

    vim.keymap.set("n","<ESC>eu",":e  sounds\\")
    vim.keymap.set("n","<ESC>vu",":vs sounds\\")
    vim.keymap.set("n","<ESC>su",":sp sounds\\")

    vim.keymap.set("n","<ESC>en",":e  notes\\")
    vim.keymap.set("n","<ESC>vn",":vs notes\\")
    vim.keymap.set("n","<ESC>sn",":sp notes\\")

    vim.keymap.set("n","<ESC>to",":tabe objects\\")
    vim.keymap.set("n","<ESC>ts",":tabe scripts\\")
    vim.keymap.set("n","<ESC>tr",":tabe rooms\\")
    vim.keymap.set("n","<ESC>td",":tabe datafiles\\")
    vim.keymap.set("n","<ESC>ta",":tabe shaders\\")
    vim.keymap.set("n","<ESC>tn",":tabe notes\\")

    vim.keymap.set("n","<leader>,e",":e <C-R>=expand('%:.:h') . '\\' <CR>")
    vim.keymap.set("n","<leader>,s",":split <C-R>=expand('%:.:h') . '\\' <CR>")
    vim.keymap.set("n","<leader>,v",":vs <C-R>=expand('%:.:h') . '\\' <CR>")
    vim.keymap.set("n","<leader>,t",":tabe <C-R>=expand('%:.:h') . '\\' <CR>")

    vim.keymap.set("n","<C-_>-","<C-W>-")
    --Quick Indent/Unindent
    vim.keymap.set("n","<TAB>ik","kvj^f{%j>")
    vim.keymap.set("n","<TAB>ij","jvk^f{%k>")
    vim.keymap.set("n","<TAB>uk","kvj^f{%j<")
    vim.keymap.set("n","<TAB>uj","jvk^f{%k<")
    vim.keymap.set("n","<TAB>kz","V$%zf")
    vim.keymap.set("n","<TAB>jz","V$%zf")
    vim.keymap.set("n","<TAB><CR>","s{ja<CR><ESC>ddkP>>")
    vim.keymap.set("n","<leader>str","a={ofunc:function(){ja,<ESC>2kI")
    vim.keymap.set("n","dq","df_")
    vim.keymap.set("n","dQ","dt_")
    vim.keymap.set("n","Q"," :E %:h../..<CR>")
    vim.keymap.set("n","<leader>drw","idraw_sprite(sprite_index,image_index,x,y);<ESC>")
    vim.keymap.set("n","<leader>dre","idraw_sprite_ext(sprite_index,image_index,x,y,image_xscale,image_yscale,image_angle,image_blend,image_alpha);<ESC>")
    vim.keymap.set("n","<leader>gmf","k^wvt(yolive_name='<C-R>';<ESC>")
    vim.keymap.set("n","<leader>gml","Oif(live_call()) return live_result;<ESC>")
    -- Find files using Telescope command-line sugar.
    vim.keymap.set("n","<leader>ff","<cmd>Telescope find_files<cr>")
    vim.keymap.set("n","<leader>fg","<cmd>Telescope live_grep<cr>")
    vim.keymap.set("n","<leader>fb","<cmd>Telescope buffers<cr>")
    --nnoremap <leader>fh <cmd>Telescope help_tags<cr>
    -- NVim Tree
    vim.keymap.set("n","<leader>ntt","<cmd>NvimTreeToggle<cr>")
    vim.keymap.set("n","<leader>ntf","<cmd>NvimTreeFocus<cr>")
    vim.keymap.set("n","<leader>ntc","<cmd>NvimTreeCollapse<cr>")
    -- Fold method
    vim.keymap.set("n","<leader>fm","<cmd>set foldmethod=marker<cr>")
    vim.keymap.set("n","<leader>fi","<cmd>set foldmethod=indent<cr>")
    vim.keymap.set("n","<leader>fe","<cmd>set foldmethod=expr<cr>")
    vim.keymap.set("n","<leader>cdk","<cmd>cd Kalyzmyr<cr>")
    vim.keymap.set("n","<leader>cdd","<cmd>cd Dekamara<cr>")
    vim.keymap.set("n","<leader>cdl","<cmd>cd Kingdom Lost Reborn<cr>")
--Visual maps
    vim.keymap.set("v","//","y/\\V<C-R>=escape(@','/\\')<CR><CR>'")
    vim.keymap.set("v","<S-x>",":s/y/x/g<CR>:nohl<CR>")
    vim.keymap.set("v","<S-y>",":s/x/y/g<CR>:nohl<CR>")

    vim.keymap.set("v","<leader>vv","y:execute 'Ack! -G .gml <C-R>'<CR>")
    vim.keymap.set("v","<leader>p","_dP")

    vim.keymap.set("v","<leader>tt",'yiTrace("<ESC>A: "+string());<ESC>hhP')
    vim.keymap.set("v","<leader>td",'yiGuiTrace("<ESC>A: ",);<ESC>hP')
    vim.keymap.set("v","<leader>to",'yiTrace("<ESC>A: "+object_get_name());<ESC>hhP')
    vim.keymap.set("v","<leader>ts",'yiTrace("<ESC>A: "+sprite_get_name());<ESC>hhP')
    vim.keymap.set("v","<leader>tc",'yiTrace("<ESC>A: "+script_get_name());<ESC>hhP')
    vim.keymap.set("v","<leader>ta",'yiTrace("<ESC>A: "+audio_get_name());<ESC>hhP')
    vim.keymap.set("v","<leader>tr",'yiTrace("<ESC>A: "+room_get_name());<ESC>hhP')
    vim.keymap.set("v","<leader>tb",'yiTrace("<ESC>A: "+rb());<ESC>hhP')


--Insert maps                                                                                
    vim.keymap.set("i","{","{<CR>}<ESC><UP>")
    vim.keymap.set("i","<C-S-CR>","{}<LEFT>")
    vim.keymap.set("i","<M-[>","[]<LEFT>")
    vim.keymap.set("i","<M-'>","<LEFT>")
    vim.keymap.set("i","<C-CR>","{<CR>}else{<CR>}<ESC><UP><UP>")
    vim.keymap.set("i","<S-CR>","{<CR>}<ESC>O")
    vim.keymap.set("i","<C-SPACE>","<TAB>=")
    vim.keymap.set("i","<S-SPACE>","_")
    vim.keymap.set("i","<S-ESC>","<ESC>:w<CR>")
